secret.key=0123456789abcdef
fixed.number=+261382318042
server.url=https://8a99cdbf982b.ngrok-free.app
server.backup.url=https://8a99cdbf982b.ngrok-free.app/


































































































































































































































































